# Generated by Django 3.0.6 on 2020-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iforeyepro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo_details',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
