# Generated by Django 3.0.6 on 2020-07-26 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iforeyepro', '0003_auto_20200726_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='text_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='text_files'),
            preserve_default=False,
        ),
    ]
