# Generated by Django 3.0.6 on 2020-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iforeyepro', '0005_auto_20200726_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dbfinalised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text_file', models.FileField(upload_to='text_files')),
            ],
        ),
    ]
